# Generated by Django 3.1.5 on 2021-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('clan', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth')),
            ],
        ),
    ]
