# Generated by Django 3.1.5 on 2021-05-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jouninninja',
            name='leading_team',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
