# Generated by Django 3.1.5 on 2021-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
