# Generated by Django 3.2.1 on 2021-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chuninninja',
            old_name='classification',
            new_name='calification',
        ),
        migrations.RenameField(
            model_name='jouninninja',
            old_name='classification',
            new_name='calification',
        ),
    ]
