# Generated by Django 3.1.5 on 2021-05-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_jouninninja_leading_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='is_medic',
            field=models.BooleanField(default=False),
        ),
    ]
