# Generated by Django 3.1.5 on 2021-05-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocations', '0001_initial'),
        ('ninjas', '0002_ninja_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='invocations',
            field=models.ManyToManyField(to='invocations.Invocation'),
        ),
    ]
