# Generated by Django 3.1.5 on 2021-05-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0003_ninja_invocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
