# Generated by Django 3.2.1 on 2021-05-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0003_ninja_user'),
        ('ninjas', '0004_ninja_gender'),
    ]

    operations = [
    ]
