# Generated by Django 3.1.5 on 2021-05-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0006_auto_20210506_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='in_mission',
            field=models.BooleanField(default=False),
        ),
    ]
