# Generated by Django 3.1.5 on 2021-05-20 16:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_attackskill_healskill'),
        ('invocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ninjas', '0007_team_in_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuninNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('clan', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth')),
                ('gender', models.CharField(max_length=10)),
                ('exam_date', models.DateField()),
                ('classification', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('invocations', models.ManyToManyField(to='invocations.Invocation')),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeninNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('clan', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth')),
                ('gender', models.CharField(max_length=10)),
                ('graduation_date', models.DateField()),
                ('assessment', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('invocations', models.ManyToManyField(to='invocations.Invocation')),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JouninNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('clan', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth')),
                ('gender', models.CharField(max_length=10)),
                ('exam_date', models.DateField()),
                ('classification', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('invocations', models.ManyToManyField(to='invocations.Invocation')),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
