# Generated by Django 3.1.5 on 2021-05-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_attackskill_healskill'),
        ('invocations', '0001_initial'),
        ('ninjas', '0008_auto_20210520_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuninninja',
            name='invocations',
            field=models.ManyToManyField(blank=True, to='invocations.Invocation'),
        ),
        migrations.AlterField(
            model_name='chuninninja',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
        migrations.AlterField(
            model_name='chuninninja',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team'),
        ),
        migrations.AlterField(
            model_name='geninninja',
            name='invocations',
            field=models.ManyToManyField(blank=True, to='invocations.Invocation'),
        ),
        migrations.AlterField(
            model_name='geninninja',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
        migrations.AlterField(
            model_name='geninninja',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team'),
        ),
        migrations.AlterField(
            model_name='jouninninja',
            name='invocations',
            field=models.ManyToManyField(blank=True, to='invocations.Invocation'),
        ),
        migrations.AlterField(
            model_name='jouninninja',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
        migrations.AlterField(
            model_name='jouninninja',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team'),
        ),
    ]
