# Generated by Django 3.1.5 on 2021-05-20 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_attackskill_healskill'),
        ('ninjas', '0009_auto_20210520_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='HokageNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('clan', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth')),
                ('gender', models.CharField(max_length=10)),
                ('hokage_number', models.IntegerField()),
                ('invocations', models.ManyToManyField(blank=True, to='invocations.Invocation')),
                ('skills', models.ManyToManyField(blank=True, to='skills.Skill')),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
