# Generated by Django 3.1.5 on 2021-05-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunais', models.IntegerField(default=0)),
                ('shurikens', models.IntegerField(default=0)),
                ('explosive_seals', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='inventory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.inventory'),
        ),
    ]
