# Generated by Django 3.1.5 on 2021-05-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_parchment'),
        ('missions', '0003_auto_20210519_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='parchment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.parchment'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='inventory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.inventory'),
        ),
    ]
