# Generated by Django 3.1.5 on 2021-05-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('missions', '0003_alter_mission_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='parchment',
        ),
        migrations.CreateModel(
            name='Parchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.inventory')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
        ),
    ]
