# Generated by Django 3.1.5 on 2021-05-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0009_auto_20210520_1213'),
        ('missions', '0004_auto_20210519_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='leader',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ninjas.jouninninja'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='inventory',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.inventory'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='team',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ninjas.team'),
        ),
        migrations.CreateModel(
            name='MissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
            ],
        ),
    ]
