# Generated by Django 3.1.5 on 2021-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_auto_20210520_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='leader',
        ),
    ]
