# Generated by Django 3.1.5 on 2021-05-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0009_auto_20210520_1213'),
        ('missions', '0007_mission_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.jouninninja'),
        ),
    ]
