# Generated by Django 3.2.1 on 2021-05-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chakra_required', models.IntegerField()),
                ('belong_to_the_village', models.BooleanField()),
                ('element', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttackSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skills.skill')),
                ('range', models.IntegerField()),
            ],
            bases=('skills.skill',),
        ),
        migrations.CreateModel(
            name='HealSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skills.skill')),
                ('speed', models.IntegerField()),
            ],
            bases=('skills.skill',),
        ),
        migrations.CreateModel(
            name='Parchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
        ),
    ]
