# Generated by Django 3.1.5 on 2021-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chakra_required', models.IntegerField()),
                ('belong_to_the_village', models.BooleanField()),
            ],
        ),
    ]
