# Generated by Django 3.1.5 on 2021-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='element',
            field=models.CharField(default='Rayo', max_length=50),
            preserve_default=False,
        ),
    ]
