# Generated by Django 3.1.5 on 2021-05-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_auto_20210527_1841'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parchment',
        ),
    ]
